export const ActionTypes = {
  SET_FORM_STATE: "SET_FORM_STATE",
  SET_USERNAME: "SET_USERNAME",
  SET_PASSWORD: "SET_PASSWORD",
  SET_EMAIL: "SET_EMAIL",
  SET_FORGOTPASS_TOGGLE: "SET_FORGOTPASS_TOGGLE",
  SET_TOKEN: "SET_TOKEN",
  SET_LOADING: "SET_LOADING",
  SET_SIGNUP_MODAL:"SET_SIGNUP_MODAL",
  SET_SIGNUP_STATE:"SET_SIGNUP_STATE",
  SET_FORGOT_PASS_MODAL:"SET_FORGOT_PASS_MODAL",
  SET_FORGOT_PASS_STATE:"SET_FORGOT_PASS_STATE",
  SET_LOGIN_STATE:"SET_LOGIN_STATE",
  SET_ALL_INTERESTS:"SET_ALL_INTERESTS",
  // LOG_IN:"LOG_IN",

  };