export const ActionTypes = {
  GET_CHAT_USERS:"GET_CHAT_USERS",
  SOCKET_CONNECTED:"SOCKET_CONNECTED",
  USERS_RECIEVED:"USERS_RECIEVED",
  ADD_MESSAGE:"ADD_MESSAGE",
  GET_MESSAGE:"GET_MESSAGE",
  GET_CHAT:"GET_CHAT",
  CHAT_RECIEVED:"CHAT_RECIEVED",
  SEND_MESSAGE:"SEND_MESSAGE",
  SAVE_SOCKET:"SAVE_SOCKET",
  SET_CHATID:"SET_CHATID",
  LAST_CHAT_RECIEVED:"LAST_CHAT_RECIEVED",
  GET_CHAT_INFO:"GET_CHAT_INFO",
  INFO_RECIEVED:"INFO_RECIEVED",
  SENT_TO_CHAT:"SENT_TO_CHAT",
  GET_PREV_MSG:"GET_PREV_MSG",
  CHANGE_CHAT:"CHANGE_CHAT"
};