export const ActionTypes = {
    SET_INFO: "SET_INFO",
    SET_ERROR: "SET_ERROR",
    SET_VERIFIED: "SET_VERIFIED",
    SET_RESEND_EMAIL_MODAL: "SET_RESEND_EMAIL_MODAL",
    SET_EMAIL:"SET_EMAIL",
    SET_LOADING:"SET_LOADING",
    SET_ERROR_MSG:"SET_ERROR_MSG",
};